/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CardColumn: typeof import('./src/components/CardList/CardColumn.vue')['default']
    CardItem: typeof import('./src/components/HorizontalCardList/CardItem.vue')['default']
    CardList: typeof import('./src/components/CardList/CardList.vue')['default']
    CardRow: typeof import('./src/components/HorizontalCardList/CardRow.vue')['default']
    HorizontalCardList: typeof import('./src/components/HorizontalCardList/HorizontalCardList.vue')['default']
    PageContainer: typeof import('./src/components/PageContainer/PageContainer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar/SearchBar.vue')['default']
    Section: typeof import('./src/components/PageContainer/Section.vue')['default']
    TabBar: typeof import('./src/components/TabBar/TabBar.vue')['default']
    TabBarItem: typeof import('./src/components/TabBar/components/TabBarItem/TabBarItem.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanField: typeof import('vant/es')['Field']
  }
}
